### ISSUE TITLE
Installation no go

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-notification#31]
```
javascript/aurelia-example-client [ jspm i aurelia-notification                       ] 4:34 PM
     Updating registry cache...
     Looking up npm:aurelia-notification
     Downloading npm:aurelia-notification@0.0.6

warn Error on processPackageConfig
     Package.json dependency aurelia-dependency-injection set to npm:aurelia-dependency-injection@^1.0.0-beta.1.2.0, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for npm:aurelia-notification.
         at /Users/rwoverdijk/projects/javascript/aurelia-example-client/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (/Users/rwoverdijk/projects/javascript/aurelia-example-client/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/Users/rwoverdijk/projects/javascript/aurelia-example-client/node_modules/rsvp/dist/rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error processing package config for npm:aurelia-notification.

warn Installation changes not saved.
```

**Comment by doktordirk** [comment]
was old version
