### ISSUE TITLE
Aurelia-Notification no longer working in webpack after recent Aurelia update

### ISSUE THREAD

**Issue by m-andrew-albright** [SpoonX/aurelia-notification#49]
I'll try to give as much context as possible, but I don't have time to hunt down the exact cause of the issue myself right now.  We are using Webpack, our project is based on the aurelia-skeleton navigation project, webpack-es2016 from around a month and a half ago to two months ago.  Doing an `npm update` renders my application broken due to the following error:

```
Unhandled rejection Error: Cannot find module './aurelia-notification'.
    at http://localhost:3001/1.bundle.js:164:42
    at webpackContextResolve (http://localhost:3001/1.bundle.js:164:90)
    at webpackContext (http://localhost:3001/1.bundle.js:161:30)
    at http://localhost:3001/bundle.js:25202:81
    at http://localhost:3001/bundle.js:136:24
    at Function.requireEnsure [as e] (http://localhost:3001/bundle.js:597:29)
    at Function.ensure [as e] (http://localhost:3001/bundle.js:134:33)
    at http://localhost:3001/bundle.js:25201:32
    at Promise._execute (http://localhost:3001/bundle.js:18030:10)
    at Promise._resolveFromExecutor (http://localhost:3001/bundle.js:20177:19)
    at new Promise (http://localhost:3001/bundle.js:19780:15)
    at WebpackLoader._import (http://localhost:3001/bundle.js:25196:13)
    at http://localhost:3001/bundle.js:25252:17
    at Promise._execute (http://localhost:3001/bundle.js:18030:10)
    at Promise._resolveFromExecutor (http://localhost:3001/bundle.js:20177:19)
    at new Promise (http://localhost:3001/bundle.js:19780:15)
```

I know this stack trace is not particularly helpful or useful, but in case it helps at all I figured I would include it.  I have not tried downloading the latest aurelia navigation skeleton project (they have released a new one which made a ton of changes)

If there is any more information I can provide, let me know.

**Comment by doktordirk** [comment]
i tried with the "aurelia-webpack-plugin": "1.0.0-beta.1.0.4", and had no problem

the new skeleton and/or aurelia-webpack-plugin didnt work for me neither. but i'll maybe better wait before trying to fix something

**Comment by m-andrew-albright** [comment]
Yeah my issue was when I tried to update to 1.0.0-beta.2.0.0

**Comment by doktordirk** [comment]
works again with plugin 4 (i think)
